// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiY9shBBA_6M3jA0gZHLWrKFuO81xs-lc',
    appId: '1:186413362942:web:1eb9b2e97ece8ce655ffaf',
    messagingSenderId: '186413362942',
    projectId: 'bookswap-5b6c5',
    authDomain: 'bookswap-5b6c5.firebaseapp.com',
    storageBucket: 'bookswap-5b6c5.firebasestorage.app',
    measurementId: 'G-QP9PEQZTKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQTJFu-qeZ-LGUFJE4uLAaNtj-A3M_ygc',
    appId: '1:186413362942:android:121773e1235eec9c55ffaf',
    messagingSenderId: '186413362942',
    projectId: 'bookswap-5b6c5',
    storageBucket: 'bookswap-5b6c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCexnbHddKyf55EAmJg_gA63oNkEKocWE',
    appId: '1:186413362942:ios:ae8d23fa350c709155ffaf',
    messagingSenderId: '186413362942',
    projectId: 'bookswap-5b6c5',
    storageBucket: 'bookswap-5b6c5.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );
}
